import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import SessionProvider from '../components/session-provider'
import { Navbar } from '@/components/navbar'
import '../styles/globals.scss'
import css from './layout.module.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={css.wrapper}>
        <SessionProvider session={session}>
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
   )
}
